@startuml
!include Style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":PutCommandParser" as PutCommandParser LOGIC_COLOR
participant "u:PutCommand" as PutCommand LOGIC_COLOR
end box

box Model
participant ":Model" as Model LOGIC_COLOR_T4
participant ":AddressBook" as AddressBook LOGIC_COLOR_T4
end box

[-> LogicManager : execute(put)
activate LogicManager

LogicManager -> PutCommandParser : parseCommand(put)
activate PutCommandParser

create PutCommand
PutCommandParser -> PutCommand
activate PutCommand

PutCommand --> PutCommandParser
deactivate PutCommand

PutCommandParser --> LogicManager : u
deactivate PutCommandParser

LogicManager -> PutCommand : execute(model)
activate PutCommand

PutCommand -> Model : putPersonIntoLineup()
activate Model

Model -> AddressBook : addPersonToLineup()
activate AddressBook

AddressBook --> Model
deactivate AddressBook

Model --> PutCommand
deactivate Model

PutCommand --> LogicManager : result
deactivate PutCommand

@enduml
