@startuml
'https://plantuml.com/activity-diagram-beta

start
:User executes add command;

if () then ([valid command])
    if () then ([candidate not in system])
        :Save candidate to system;
    else ([else])
        :Show duplicate candidate message;
    endif
else ([invalid command])
    :Show invalid command message;
endif
stop

@enduml
