@startuml
'https://plantuml.com/sequence-diagram
!include style.puml


box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":AddBuyerCommandParser" as AddBuyerCommandParser LOGIC_COLOR
participant "d:AddBuyerCommand" as AddBuyerCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

box Storage STORAGE_COLOR_T1
participant ":Storage" as Storage STORAGE_COLOR_T2

[-> LogicManager : execute("delete 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("addbuyer n/David p/12345678")
activate AddressBookParser

create AddBuyerCommandParser
AddressBookParser -> AddBuyerCommandParser
activate AddBuyerCommandParser

AddBuyerCommandParser --> AddressBookParser
deactivate AddBuyerCommandParser

AddressBookParser -> AddBuyerCommandParser : parse("n/David p/12345678")
activate AddBuyerCommandParser

create AddBuyerCommand
AddBuyerCommandParser -> AddBuyerCommand
activate AddBuyerCommand

AddBuyerCommand --> AddBuyerCommandParser
deactivate AddBuyerCommand

AddBuyerCommandParser --> AddressBookParser
deactivate AddBuyerCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddBuyerCommandParser -[hidden]-> AddressBookParser
destroy AddBuyerCommandParser

AddressBookParser --> LogicManager
deactivate AddressBookParser

LogicManager -> AddBuyerCommand : execute()
activate AddBuyerCommand

AddBuyerCommand -> Model : addBuyer()
activate Model

Model --> AddBuyerCommand
deactivate Model



create CommandResult
AddBuyerCommand -> CommandResult
activate CommandResult

CommandResult --> AddBuyerCommand
deactivate CommandResult

AddBuyerCommand --> LogicManager : result
deactivate AddBuyerCommand

LogicManager --> Storage : saveBuyerAddressBook()
activate Storage

Storage --> LogicManager
deactivate Storage

[<--LogicManager : result
deactivate LogicManager
@enduml
