@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":AddGroupCommandParser" as AddGroupCommandParser LOGIC_COLOR
participant "g:AddGroupCommand" as AddGroupCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("addgroup g/example")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("addgroup g/example")
activate AddressBookParser

create AddGroupCommandParser
AddressBookParser -> AddGroupCommandParser
activate AddGroupCommandParser

AddGroupCommandParser --> AddressBookParser
deactivate AddGroupCommandParser

AddressBookParser -> AddGroupCommandParser : parse("g/example")
activate AddGroupCommandParser

create AddGroupCommand
AddGroupCommandParser -> AddGroupCommand
activate AddGroupCommand

AddGroupCommand --> AddGroupCommandParser : g
deactivate AddGroupCommand

AddGroupCommandParser --> AddressBookParser : g
deactivate AddGroupCommandParser

'Hidden arrow to position the destroy marker below the end of the activation bar.
AddGroupCommandParser -[hidden]-> AddressBookParser
destroy AddGroupCommandParser

AddressBookParser --> LogicManager : g
deactivate AddressBookParser

LogicManager -> AddGroupCommand : execute()
activate AddGroupCommand

AddGroupCommand -> Model : addGroup(example)
activate Model

Model --> AddGroupCommand
deactivate Model

create CommandResult
AddGroupCommand -> CommandResult
activate CommandResult

CommandResult --> AddGroupCommand
deactivate CommandResult

AddGroupCommand --> LogicManager : result
deactivate AddGroupCommand

[<--LogicManager
deactivate LogicManager
@enduml
