@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ArchDukeParser" as ArchDukeParser LOGIC_COLOR
participant ":AddGroupCommandParser" as AddGroupCommandParser LOGIC_COLOR
participant "a:AddGroupCommand" as AddGroupCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("addgroup g/example")
activate LogicManager

LogicManager -> ArchDukeParser : parseCommand("addgroup g/example")
activate ArchDukeParser

create AddGroupCommandParser
ArchDukeParser -> AddGroupCommandParser
activate AddGroupCommandParser

AddGroupCommandParser --> ArchDukeParser
deactivate AddGroupCommandParser

ArchDukeParser -> AddGroupCommandParser : parse("g/example")
activate AddGroupCommandParser

create AddGroupCommand
AddGroupCommandParser -> AddGroupCommand
activate AddGroupCommand

AddGroupCommand --> AddGroupCommandParser : a
deactivate AddGroupCommand

AddGroupCommandParser --> ArchDukeParser : a
deactivate AddGroupCommandParser

'Hidden arrow to position the destroy marker below the end of the activation bar.
AddGroupCommandParser -[hidden]-> ArchDukeParser
destroy AddGroupCommandParser

ArchDukeParser --> LogicManager : a
deactivate ArchDukeParser

LogicManager -> AddGroupCommand : execute()
activate AddGroupCommand

AddGroupCommand -> Model : hasGroup(example)
activate Model

Model --> AddGroupCommand
deactivate Model

AddGroupCommand -> Model : addGroup(example)
activate Model

Model --> AddGroupCommand
deactivate Model

create CommandResult
AddGroupCommand -> CommandResult
activate CommandResult

CommandResult --> AddGroupCommand : result
deactivate CommandResult

AddGroupCommand --> LogicManager : result
deactivate AddGroupCommand

[<--LogicManager
deactivate LogicManager
@enduml
