@startuml
!include style.puml

title Add Student

box Model MODEL_COLOR_T1
participant ":ModelManager" as ModelManager MODEL_COLOR
participant ":TAssist" as TAssist MODEL_COLOR
participant ":UniqueStudentList" as UniqueStudentList MODEL_COLOR
end box

[->ModelManager : addEntity(student)
activate ModelManager

ModelManager -> TAssist : addStudent(student)
activate TAssist

TAssist -> UniqueStudentList : add(student)
activate UniqueStudentList

UniqueStudentList --> TAssist
deactivate UniqueStudentList

TAssist --> ModelManager
deactivate TAssist

[<--ModelManager
deactivate ModelManager
@enduml
