@startuml
!include style.puml

box Model MODEL_COLOR_T1
participant  ":AddressBook" as AddressBook MODEL_COLOR
participant "p:Person" as Person MODEL_COLOR
participant "tags:UniqueTagList" as UniqueTagList MODEL_COLOR
end box

[-> AddressBook : setTags(tags)
activate AddressBook
loop for each p in persons
    AddressBook -> Person : stripTagsFromPerson(p, tags)
    Person --> AddressBook
end

AddressBook -> UniqueTagList : setTags(tags)
activate UniqueTagList
UniqueTagList --> AddressBook
deactivate UniqueTagList
[<-- AddressBook

@enduml
