@startuml
!include style.puml

box Model MODEL_COLOR_T1
participant ":AddressBook" as AddressBook MODEL_COLOR
participant ":Person" as Person MODEL_COLOR
participant ":UniquePersonList" as UniquePersonList MODEL_COLOR
end box

[-> AddressBook : setPersons(persons)
activate AddressBook
loop for each p in persons
    AddressBook -> Person : addTagsNotInList(p)
    activate Person
    Person --> AddressBook
    deactivate Person
end
AddressBook -> UniquePersonList : setPersons(persons)
activate UniquePersonList
UniquePersonList --> AddressBook
deactivate UniquePersonList
[<-- AddressBook
deactivate AddressBook

@enduml
