@startuml
start
:User executes the 'adds' command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([valid command format])
    :Parses the command\nusing AddServiceCommandParser;
    if () then ([valid parameters])
        :Add new service to model;
    else ([else])
        :Shows an invalid\nparameters error message;
        stop
    endif
    if () then ([user is on Services tab])
    else ([else])
        :Switch to Services tab;
    endif
    :Displays updated service list;
else ([else])
    :Shows an invalid command error message;
endif
stop
@enduml
