@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":UniBookParser" as UniBookParser LOGIC_COLOR
participant ":AddCommandParser" as AddCommandParser LOGIC_COLOR
participant "ac:AddCommand" as AddCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("add o/module n/Software Engineering m/CS2103", true, false)
activate LogicManager

LogicManager -> UniBookParser : parseCommand("add o/module n/Software Engineering m/CS2103")
activate UniBookParser

create AddCommandParser
UniBookParser -> AddCommandParser
activate AddCommandParser

create AddCommand
AddCommandParser -> AddCommand
activate AddCommand

AddCommand --> AddCommandParser : ac
deactivate AddCommand

AddCommandParser --> UniBookParser : ac

deactivate AddCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddCommandParser -[hidden]-> UniBookParser
destroy AddCommandParser

UniBookParser --> LogicManager : ac
deactivate UniBookParser

LogicManager -> AddCommand : execute(m, true, false)
activate AddCommand

AddCommand -> Model : m.addModule(Module)
activate Model

Model --> AddCommand
deactivate Model

create CommandResult
AddCommand -> CommandResult
activate CommandResult

CommandResult --> AddCommand
deactivate CommandResult

AddCommand --> LogicManager : result
deactivate AddCommand

[<--LogicManager
deactivate LogicManager
@enduml
