@startuml
!include style.puml

title Adding Commands to CommandHistory\n

box "Logic" LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
end box

box "Model" MODEL_COLOR_T1
participant "model:Model" as Model MODEL_COLOR
participant ":CommandHistory" as CommandHistory MODEL_COLOR
end box

[-> LogicManager : execute(commandText)
activate LogicManager LOGIC_COLOR

LogicManager -> Model : addToCommandHistory(commandText)
activate Model MODEL_COLOR

Model -> CommandHistory : addToHistory(commandText)
activate CommandHistory MODEL_COLOR

CommandHistory --> Model
deactivate CommandHistory

Model --> LogicManager
deactivate Model

[<--LogicManager
deactivate LogicManager
@enduml
