@startuml
!include style.puml

Actor User as user USER_COLOR
Participant ":UI" as ui UI_COLOR
Participant ":Logic" as logic LOGIC_COLOR
Participant ":Model" as model MODEL_COLOR
Participant ":Storage" as storage STORAGE_COLOR

user -[USER_COLOR]> ui : "deletec 1"
activate ui UI_COLOR

ui -[UI_COLOR]> logic : execute("deletec 1")
activate logic LOGIC_COLOR

loop bookings of the\n customer (index 1)\n that is in the future
    logic -> model : deleteBooking(b) \t\t\t
    model --> logic
end
activate model MODEL_COLOR
logic -[LOGIC_COLOR]> model : deleteCustomer(c)

model -[MODEL_COLOR]-> logic
deactivate model

logic -[LOGIC_COLOR]> storage : saveTrackBeau(trackBeau)
activate storage STORAGE_COLOR

storage -[STORAGE_COLOR]> storage : Save to file
activate storage STORAGE_COLOR_T1
storage --[STORAGE_COLOR]> storage
deactivate storage

storage --[STORAGE_COLOR]> logic
deactivate storage

logic --[LOGIC_COLOR]> ui
deactivate logic

ui--[UI_COLOR]> user
deactivate ui
@enduml
