@startuml
!include <material/common>
!include <material/account>
!include <material/file_document>
!include Style.puml

skinparam PackagePadding 1

Package " "<<Rectangle>>{
    Class UI<<Ui>>
    Class Logic<<Logic>>
    Class Storage<<Storage>>
    Class Model<<Model>>

    skinparam ClassBorderColor<<Main>> grey
    skinparam ClassFontColor<<Main>> grey
    hide <<Main>> stereotype
    Class Main<<Main>>

    skinparam ClassBorderColor<<Commons>> LOGIC_COLOR_T2
    skinparam ClassFontColor<<Commons>> LOGIC_COLOR_T2
    hide <<Commons>> stereotype
    Class Commons<<Commons>>
}

Class "<$ma_account>" as User<<Hidden>>
Class "<$ma_file_document>" as File<<Hidden>>

UI -[UI_COLOR]> Logic
UI -right[UI_COLOR]-> Model
Logic -[LOGIC_COLOR]-> Storage
Logic -down[LOGIC_COLOR]-> Model
Main -[#grey]-> UI
Main -[#grey]-> Logic
Main -[#grey]-> Storage
Main -up[#grey]-> Model
Main -down[hidden]-> Commons

Storage -up[STORAGE_COLOR].> Model
Storage .right[STORAGE_COLOR].>File
User ..> UI
@enduml
