@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ArchDukeParser" as ArchDukeParser LOGIC_COLOR
participant ":AssignCommandParser" as AssignCommandParser LOGIC_COLOR
participant "g:AssignCommand" as AssignCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "model:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("assign 1 g/example")
activate LogicManager

LogicManager -> ArchDukeParser : parseCommand("assign 1 g/example")
activate ArchDukeParser

create AssignCommandParser
ArchDukeParser -> AssignCommandParser
activate AssignCommandParser

AssignCommandParser --> ArchDukeParser
deactivate AssignCommandParser

ArchDukeParser -> AssignCommandParser : parse("1 g/example")
activate AssignCommandParser

create AssignCommand
AssignCommandParser -> AssignCommand
activate AssignCommand

AssignCommand --> AssignCommandParser : g
deactivate AssignCommand

AssignCommandParser --> ArchDukeParser : g
deactivate AssignCommandParser

'Hidden arrow to position the destroy marker below the end of the activation bar.
AssignCommandParser -[hidden]-> ArchDukeParser
destroy AssignCommandParser

ArchDukeParser --> LogicManager : g
deactivate ArchDukeParser

LogicManager -> AssignCommand : execute()
activate AssignCommand

AssignCommand -> Model : assignPerson(p, example)
activate Model

Model --> AssignCommand
deactivate Model

create CommandResult
AssignCommand -> CommandResult
activate CommandResult

CommandResult --> AssignCommand : result
deactivate CommandResult

AssignCommand --> LogicManager : result
deactivate AssignCommand

[<--LogicManager
deactivate LogicManager
@enduml
