@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title Initial state

package State {
    class Student as "__Student : David__"
    class Lesson as "__Lesson: Sec 2 Math__"
    class enrolledStudents as "__EnrolledStudents: enrolledStudents__" {
        List<Student> : enrolledStudents
    }
    class enrolledLessons as "__EnrolledLessons: enrolledLessons__" {
        List<Lesson> : enrolledLessons
    }
}
Student -[hidden]-> enrolledLessons
Lesson -[hidden]-> enrolledStudents
hide enrolledStudents
hide enrolledLessons

@end
