@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title Final state

package State {
    class Student as "__Student : David__"
    class Lesson as "__Lesson: Sec 2 Math__"
    class enrolledStudents as "__EnrolledStudents: enrolledStudents__"
    class enrolledLessons as "__EnrolledLessons: enrolledLessons__"
}
Student -down-> enrolledLessons
enrolledLessons -up-> Lesson
enrolledStudents -up-> Student
Lesson -down-> enrolledStudents
@end