@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniqueclientList
AddressBook *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueclientList
UniqueTagList -[hidden]down- UniqueclientList

UniqueTagList *-right-> "*" Tag
UniqueclientList -right-> client

client -up-> "*" Tag

client *--> Name
client *--> Phone
client *--> Email
client *--> Address
@enduml
