@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

PetBook *-right-> "1" UniquePetList
PetBook *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniquePetList
UniqueTagList -[hidden]down- UniquePetList

UniqueTagList *-right-> "*" Tag
UniquePetList -right-> Pet

Pet -up-> "0..1" Tag

Pet *--> Name
Pet *--> OwnerName
Pet *--> Phone
Pet *--> Address
Pet *--> "0..1" Diet
Pet *--> "0..1" Appointment
Pet *--> Tag
Pet *--> AttendanceHashMap
@enduml

