@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

TAssist *-right-> "1" UniqueClassGroupList
UniqueClassGroupList -right-> ClassGroup

ClassGroup *--> ClassGroupId
ClassGroup *--> ClassGroupType
ClassGroup --> TaModule
ClassGroup --> "~*" Student
ClassGroup *--> "~*" Lesson

Lesson *--> WeekId
Lesson *--> "~*" StudentAttendance

StudentAttendance *--> Student
StudentAttendance *--> Attendance
@enduml
