@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePersonList
AddressBook *-right-> "1" UniqueTeamList
AddressBook *-right-> "1" UniqueSkillList
UniqueSkillList -[hidden]down- UniqueTeamList
UniqueTeamList -[hidden]down- UniquePersonList

UniqueSkillList *-right-> "*" Skill
UniqueTeamList *-right-> "*" Team
Skill -[hidden]down- Team
UniquePersonList -right-> Person

Person -up-> "*" Team
Person -up-> "*" Skill

Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> GithubUsername
@enduml
