@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ChargeCommandParser" as ChargeCommandParser LOGIC_COLOR
participant "c:ChargeCommand" as ChargeCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

[-> LogicManager : execute("charge 1 m/04-2022 c/200")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("charge 1 m/04-2022 c/200")
activate AddressBookParser

create ChargeCommandParser
AddressBookParser -> ChargeCommandParser
activate ChargeCommandParser

ChargeCommandParser --> AddressBookParser
deactivate ChargeCommandParser

AddressBookParser -> ChargeCommandParser : parse("1 m/04-2022 c/200")
activate ChargeCommandParser

create ChargeCommand
ChargeCommandParser -> ChargeCommand
activate ChargeCommand

ChargeCommand --> ChargeCommandParser : c
deactivate ChargeCommand

ChargeCommandParser --> AddressBookParser : c
deactivate ChargeCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ChargeCommandParser -[hidden]-> AddressBookParser
destroy ChargeCommandParser

AddressBookParser --> LogicManager : c
deactivate AddressBookParser

LogicManager -> ChargeCommand : execute()
activate ChargeCommand

create CommandResult
ChargeCommand -> CommandResult
activate CommandResult

CommandResult --> ChargeCommand
deactivate CommandResult

ChargeCommand --> LogicManager : result
deactivate ChargeCommand

[<--LogicManager
deactivate LogicManager
@enduml
