@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR_T4
skinparam classBackgroundColor MODEL_COLOR
skinparam classAttributeFontColor BackgroundColor
show members

title CommandHistory Class Diagram

package Logic {
    class LogicManager
}

package Model {
Class "<<interface>>\nModel" as Model

    class ModelManager {
        addToCommandHistory()
        getCommandHistory()
    }

    class CommandHistory {
        List<>: previousCommands
        addToHistory(commandText: String)
        popPreviousCommand()
        clearHistory()
    }
}

LogicManager -> Model
Model <|- ModelManager
ModelManager -down-> CommandHistory

@enduml
