@startuml
start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.
if () then ([command undo or redo])

else ([else])
    :Phrase and run command;
    if () then ([command updates the HustleBook storage])
        :Save HustleBook state to historyList;
        :Update currStatePointer;
    else ([command fails execution])
    endif
endif
stop
@enduml
