@startuml
!include style.puml

package Logic {
    class "<<interface>>\nLogic" as Logic
    class LogicManager
}

package Model {
    class "<<interface>>\nModel" as Model
    class ModelManager
}

package Storage {
    class "<<interface>>\nStorage" as Storage
    class StorageManager
}

class HiddenOutside<<Hidden>>
HiddenOutside ..> Logic

LogicManager .up.|> Logic
ModelManager .up.|> Model
StorageManager .up.|> Storage

LogicManager --> Model
LogicManager --> Storage
@enduml
