@startuml
!include style.puml

package Logic {
Class "<<interface>>\nLogic" as Logic
Class LogicManager
}

package Model {
Class "<<interface>>\nModel" as Model
Class ModelManager
}

package Storage {
Class "<<interface>>\nStorage" as Storage
Class StorageManager
}

Class HiddenOutside<<Hidden>>
HiddenOutside ..> Logic

LogicManager .up.|> Logic
ModelManager .up.|> Model
StorageManager .up.|> Storage

LogicManager --> Model
LogicManager --> Storage
@enduml
