@startuml
!include Style.puml

Package Logic as LogicPackage<<Logic>> {
    class "<<interface>>\nLogic" as Logic<<Logic>>
    class LogicManager<<Logic>>
}

Package Model as ModelPackage<<Model>> {
    class "<<interface>>\nModel" as Model<<Model>>
    class ModelManager<<Model>>
}

Package Storage as StoragePack<<Store>> {
    class "<<interface>>\nStorage" as Storage<<Storage>>
    class StorageManager<<Storage>>
}

class HiddenOutside<<Hidden>>
HiddenOutside ..> Logic

LogicManager .up[LOGIC_COLOR].|> Logic
ModelManager .up[MODEL_COLOR].|> Model
StorageManager .up[STORAGE_COLOR].|> Storage

LogicManager -[LOGIC_COLOR]-> Model
LogicManager -[LOGIC_COLOR]-> Storage
@enduml
