@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":HustleBookParser" as HustleBookParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "d:DeleteCommand" as DeleteCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete John")
activate LogicManager

LogicManager -> HustleBookParser : parseCommand("delete John")
activate HustleBookParser

create DeleteCommandParser
HustleBookParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> HustleBookParser
deactivate DeleteCommandParser

HustleBookParser -> DeleteCommandParser : parse("John")
activate DeleteCommandParser

DeleteCommandParser -> Model : new Name("John")
activate Model

Model --> DeleteCommandParser : name
deactivate Model

create DeleteCommand
DeleteCommandParser -> DeleteCommand : new DeleteCommand(name)
activate DeleteCommand

DeleteCommand --> DeleteCommandParser : d
deactivate DeleteCommand

DeleteCommandParser --> HustleBookParser : d
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> HustleBookParser
destroy DeleteCommandParser

HustleBookParser --> LogicManager : d
deactivate HustleBookParser

LogicManager -> DeleteCommand : execute()
activate DeleteCommand

DeleteCommand -> Model : getPersonListIndex(name)
activate Model

Model --> DeleteCommand : index
deactivate Model

DeleteCommand -> Model : deletePerson(index)
activate Model

Model --> DeleteCommand
deactivate Model

create CommandResult
DeleteCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteCommand
deactivate CommandResult

DeleteCommand --> LogicManager : result
deactivate DeleteCommand

[<--LogicManager
deactivate LogicManager
@enduml
