@startuml
!include style.puml

box Model MODEL_COLOR_T1
participant ":ModelManager" as ModelManager MODEL_COLOR
participant ":TAssist" as TAssist MODEL_COLOR
participant ":UniqueClassGroupList" as UniqueClassGroupList MODEL_COLOR
end box

title Delete ClassGroup

[--> ModelManager : deleteEntity(CLASS)
activate ModelManager

ModelManager -> TAssist : removeClassGroup(CLASS)
activate TAssist

TAssist -> UniqueClassGroupList : remove(key)
activate UniqueClassGroupList

UniqueClassGroupList --> TAssist
deactivate UniqueClassGroupList

TAssist --> ModelManager
deactivate TAssist

[<--ModelManager
deactivate ModelManager

@enduml
