@startuml
!include Style.puml
!include SequenceStyle.puml

box Logic LOGIC_COLOR_LIGHT
participant ":LogicManager" as LogicManager<<Logic>>
participant ":IBookParser" as IBookParser<<Logic>>
participant ":DeleteCommandParser" as DeleteCommandParser<<Logic>>
participant "d:DeleteCommand" as DeleteCommand<<Logic>>
participant ":CommandResult" as CommandResult<<Logic>>
end box

box Model MODEL_COLOR_LIGHT
participant ":Model" as Model<<Model>>
end box

[-> LogicManager : execute("delete 1")
activate LogicManager

LogicManager -> IBookParser : parseCommand("delete 1")
activate IBookParser

create DeleteCommandParser
IBookParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> IBookParser
deactivate DeleteCommandParser

IBookParser -> DeleteCommandParser : parse("1")
activate DeleteCommandParser

create DeleteCommand
DeleteCommandParser -> DeleteCommand
activate DeleteCommand

DeleteCommand --> DeleteCommandParser
deactivate DeleteCommand

DeleteCommandParser --> IBookParser : d
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> IBookParser
destroy DeleteCommandParser

IBookParser --> LogicManager : d
deactivate IBookParser

LogicManager -> DeleteCommand : execute()
activate DeleteCommand

DeleteCommand -> Model : deleteProduct(1)
activate Model

Model --> DeleteCommand
deactivate Model

create CommandResult
DeleteCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteCommand
deactivate CommandResult

DeleteCommand --> LogicManager : result
deactivate DeleteCommand

[<--LogicManager
deactivate LogicManager
@enduml
