@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title Initial state

package State {
    class State1 as "__ta0:TAssist__"
    class ClassGroup1 as "__c1:ClassGroup__"
    class ClassGroup2 as "__c2:ClassGroup__"
}

State1 *--> ClassGroup1
State1 *--> ClassGroup2
@end
