@startuml
'https://plantuml.com/activity-diagram-beta

start
:User inputs Edit Command with index and field prefixes;

if () then ([Fields have wrong prefixes || \n Index is out of range || \n Fields with wrong format])
    :Throws ParseException;
    else (                [Else])

    if () then ([New field values to be \n are the same as the \n corresponding edited field \n values of the person])
        :CommandException;

    else (            [Else])

    if () then ([Edited field value that needs \nto be unique already \nexists in the address book])
    : Throws CommandException;
    else (            [Else])
        :Field values of person in \n the addressbook is updated;
        :Returns Message to user indicating Success;
        :ResultDisplay prints result to user;
   endif
endif
stop
@enduml
