@startuml
'https://plantuml.com/activity-diagram-beta

start
:User input email command;
:Email Window opens;

If () then ([User wishes to copy email to clipboard])
    :Click on copy email button;

    else ([User does not wish to copy emails])
    :User does nothing;

    endif
    :Close Email Window;

stop

@enduml
