@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":TrackermonParser" as TrackermonParser LOGIC_COLOR
participant ":ExportCommand" as ExportCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR

box Storage STORAGE_COLOR_T1
participant "jfm:JsonFileManager" as JsonFileManager STORAGE_COLOR
box

-> LogicManager : execute("export")
activate LogicManager

LogicManager -> TrackermonParser : parseCommand("export")
activate TrackermonParser

create ExportCommand
TrackermonParser -> ExportCommand :
activate ExportCommand

ExportCommand --> TrackermonParser
deactivate ExportCommand
deactivate TrackermonParser

LogicManager -> ExportCommand : execute(model)
activate ExportCommand

create JsonFileManager
ExportCommand -> JsonFileManager :
activate JsonFileManager

JsonFileManager --> ExportCommand :
deactivate JsonFileManager

ExportCommand -> JsonFileManager : exportFile(model.getShowListFilePath)
activate JsonFileManager

JsonFileManager --> ExportCommand : result
deactivate JsonFileManager

create CommandResult
ExportCommand -> CommandResult :
activate CommandResult

CommandResult --> ExportCommand
deactivate CommandResult

ExportCommand --> LogicManager : result
deactivate ExportCommand

<-- LogicManager
deactivate LogicManager

@enduml
