@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant "fp:FilterCommandParser" as FilterCommandParser LOGIC_COLOR
participant "f:FilterCommand" as FilterCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("filter byTags/beagle")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("filter byTags/beagle")
activate AddressBookParser

AddressBookParser -> FilterCommandParser: parse("filter byTags/beagle)
activate FilterCommandParser

create FilterCommand
FilterCommandParser -> FilterCommand
activate FilterCommand

FilterCommand --> FilterCommandParser
deactivate FilterCommand

FilterCommandParser --> AddressBookParser: f
deactivate FilterCommandParser

AddressBookParser --> LogicManager: fp
deactivate AddressBookParser

LogicManager -> FilterCommand: execute()
activate FilterCommand

FilterCommand -> Model: updateFilteredPetList()
activate Model

Model --> FilterCommand
deactivate Model

FilterCommand -> Model: getFilteredPetList()
activate Model

Model --> FilterCommand
deactivate Model

FilterCommand --> LogicManager: result
deactivate FilterCommand
FilterCommand -[hidden]-> LogicManager : result
destroy FilterCommand


[<--LogicManager
deactivate LogicManager

@enduml
