@startuml
!include style.puml

Actor User as user USER_COLOR
Participant ":UI" as ui UI_COLOR
Participant ":Logic" as logic LOGIC_COLOR
Participant ":Model" as model MODEL_COLOR

user -[USER_COLOR]> ui : "filter l/1 s/s"
activate ui UI_COLOR

ui -[UI_COLOR]> logic : execute("filter l/1 s/s")
activate logic LOGIC_COLOR

logic -[LOGIC_COLOR]> model : updateFilteredStudentList()
activate model MODEL_COLOR

model -[MODEL_COLOR]> model :
activate model MODEL_COLOR_T1

model -[MODEL_COLOR]-> logic
deactivate model



logic --[LOGIC_COLOR]> ui
deactivate logic

ui--[UI_COLOR]> user
deactivate ui
@enduml