@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant "p:FilterCommandParser" as FilterCommandParser LOGIC_COLOR
participant "f:FitlerCommand" as FilterCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "s:StudentHasLabPredicate" as StudentHasLabPredicate MODEL_COLOR
end box

[-> FilterCommandParser : parse("l/1 s/s")
activate FilterCommandParser

create StudentHasLabPredicate
FilterCommandParser -> StudentHasLabPredicate : StudentHasLabPredicate(labToFilter)
activate StudentHasLabPredicate
StudentHasLabPredicate --> FilterCommandParser
deactivate StudentHasLabPredicate

create FilterCommand
FilterCommandParser -> FilterCommand : FilterCommand(s)
activate FilterCommand
FilterCommand --> FilterCommandParser
deactivate FilterCommand

[<-- FilterCommandParser : f

@enduml
