@startuml
!pragma useVerticalIf on
start
:User executes filter command;
switch ()
case ( [field == "byTags/"] )
    :Filter pet list by tags given as filter word;
case ( [field == "byDate/"] )
    :Filter pet list by date given as filter word;
case ( [keyword == "byOwner/"] )
    :Filter pet list by owner name given as filter word;
endswitch

:Return filtered list;

stop

@enduml
