@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Class "FindCommand" as FindCommand
Command <|-- FindCommand
FindCommand o--right "1" Predicate : contains
FindPersonDescriptor .up. FindCommand

Name "*" -up-* FindPersonDescriptor
Phone "*" -up-* FindPersonDescriptor
Address "*" -up-* FindPersonDescriptor
Tag "*" -up-* FindPersonDescriptor

FindOrPredicateParser .right. FindCommand
FindOrPredicateParser .right. FindPersonDescriptor

FindAndPredicateParser .up. FindCommand
FindAndPredicateParser .up. FindPersonDescriptor
@enduml
