@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager"  as LogicManager LOGIC_COLOR
participant ":FindCommand"  as FindCommand LOGIC_COLOR
end box
box Person MODEL_COLOR_T1
participant ":Model"  as Model MODEL_COLOR
end box
box Logic LOGIC_COLOR_T1
participant ":CommandResult"  as CommandResult LOGIC_COLOR
end box

LogicManager -> FindCommand : execute
activate FindCommand
FindCommand -> Model : updateFilteredPersonList
activate Model
Model --> FindCommand
deactivate Model
FindCommand -> CommandResult : new
activate CommandResult
CommandResult -> CommandResult : new
activate CommandResult
CommandResult --> CommandResult
deactivate CommandResult
CommandResult --> FindCommand
deactivate CommandResult
return
@enduml
