@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

class "{abstract}\nCommand" as Command
class "FindCommand"
class "CombineContainsPredicateKeywords"
class "{abstract}\nFieldContainsKeywordsPredicate" as FieldContainsKeywordsPredicate
class "<<interface>>\nPredicate<Person>"
Class CommandResult

package Model{
Class HiddenModel #FFFFFF
}


Command .right.> Model
"FindCommand" -up-|> Command
FieldContainsKeywordsPredicate .up.|> "<<interface>>\nPredicate<Person>"
"CombineContainsPredicateKeywords" --|> FieldContainsKeywordsPredicate
"CombineContainsPredicateKeywords" -left-> "1" "FindCommand"
Command .up.> CommandResult : produces >
@enduml
