@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":FindTransactionParser" as FindTransactionParser LOGIC_COLOR
participant "a:FindTransactionCommand" as FindTransactionCommand LOGIC_COLOR
participant "tp:TransactionPredicateBuilder" as TransactionPredicateBuilder LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("findTransaction 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("findTransaction 1")
activate AddressBookParser

create FindTransactionParser
AddressBookParser -> FindTransactionParser
activate FindTransactionParser

FindTransactionParser --> AddressBookParser
deactivate FindTransactionParser

AddressBookParser -> FindTransactionParser : parse(1)
activate FindTransactionParser

create FindTransactionCommand
FindTransactionParser -> FindTransactionCommand
activate FindTransactionCommand

create TransactionPredicateBuilder
FindTransactionCommand --> TransactionPredicateBuilder
activate TransactionPredicateBuilder

TransactionPredicateBuilder --> FindTransactionCommand : tp
deactivate TransactionPredicateBuilder

FindTransactionCommand --> FindTransactionParser : a
deactivate FindTransactionCommand

FindTransactionParser --> AddressBookParser : a
deactivate FindTransactionParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
FindTransactionParser -[hidden]-> AddressBookParser
destroy FindTransactionParser

AddressBookParser --> LogicManager : a
deactivate AddressBookParser

LogicManager -> FindTransactionCommand : execute()
activate FindTransactionCommand

FindTransactionCommand -> Model : Get person's identifier at index 1.
activate Model
Model --> FindTransactionCommand : personId
deactivate Model

FindTransactionCommand -> TransactionPredicateBuilder : tp.createTransactionPredicate(personId)
activate TransactionPredicateBuilder

TransactionPredicateBuilder -[hidden]-> FindTransactionCommand
TransactionPredicateBuilder --> FindTransactionCommand : predicate
deactivate TransactionPredicateBuilder

TransactionPredicateBuilder -[hidden]> FindTransactionCommand
destroy TransactionPredicateBuilder

FindTransactionCommand -> Model : updateFilteredTransaction(predicate)
activate Model

Model -[hidden]-> FindTransactionCommand
Model -[hidden]-> FindTransactionCommand
Model --> FindTransactionCommand
deactivate Model

FindTransactionCommand -[hidden]-> FindTransactionCommand
create CommandResult
FindTransactionCommand -> CommandResult
activate CommandResult

CommandResult --> FindTransactionCommand : result
deactivate CommandResult

FindTransactionCommand --> LogicManager : result
deactivate FindTransactionCommand
'Hidden arrow to position the destroy marker below the end of the activation bar.
FindTransactionCommand -[hidden]-> AddressBookParser
destroy FindTransactionCommand

[<--LogicManager
deactivate LogicManager
@enduml
