@startuml
'https://plantuml.com/activity-diagram-beta

start
:User input list command;

if () then ([User inputted additional\nparameters besides just "list"])
    : Tracey throws ParseException;

    else ([Else])
        :Show the user a list of\nstudents with their particulars;
        :Send a SUCCESS message;

endif
:A response is returned to user;
stop

@enduml
