@startuml
!include style.puml

'Local overrides (copy this section)
'Change the color here
!$theme_color = LOGIC_COLOR

skinparam TitleFontColor $theme_color
skinparam Class {
    FontColor $theme_color
    StereotypeFontColor $theme_color
    BorderColor $theme_color
    FontColor<<Hidden>> #FFFFFF
    StereotypeFontColor<<Hidden>> #FFFFFF
    BorderColor<<Hidden>> #FFFFFF
}
'End of local overrides

package Logic {
    class IBookParser
    class XYZCommand
    class CommandResult
    class "{abstract}\nCommand" as Command


    class "<<interface>>\nLogic" as Logic
    class LogicManager
}

package Model {
    class HiddenModel<<Hidden>>
}

package Storage {
}

class HiddenOutside<<Hidden>>
HiddenOutside ..> Logic

LogicManager .right.|> Logic
LogicManager -right->"1" IBookParser
IBookParser ..> XYZCommand : creates >

XYZCommand -up-|> Command
LogicManager .left.> Command : executes >

LogicManager --> Model
LogicManager --> Storage
Storage --[hidden] Model
Command .[hidden]up.> Storage
Command .right.> Model
note right of XYZCommand: XYZCommand = AddCommand, \nFindCommand, etc

Logic ..> CommandResult
LogicManager .down.> CommandResult
Command .up.> CommandResult : produces >
@enduml
