@startuml
!include style.puml

$OverrideTheme(LOGIC_COLOR)

package Logic {
    class IBookParser
    class XYZCommand
    class CommandResult
    class "{abstract}\nCommand" as Command


    class "<<interface>>\nLogic" as Logic
    class LogicManager
}

package Model <<Rectangle>> {
}

package Storage <<Rectangle>> {
}

class HiddenOutside<<Hidden>>
HiddenOutside ..> Logic

LogicManager .right.|> Logic
LogicManager -right->"1" IBookParser
IBookParser ..> XYZCommand : creates >

XYZCommand -up-|> Command
LogicManager .left.> Command : executes >

LogicManager --> Model
LogicManager --> Storage
Storage --[hidden] Model
Command .[hidden]up.> Storage
Command .right.> Model
note right of XYZCommand: XYZCommand = AddCommand, \nFindCommand, etc

Logic ..> CommandResult
LogicManager .down.> CommandResult
Command .up.> CommandResult : produces >
@enduml
