@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Logic {

Class "<<Interface>>\nLogic" as Logic
Class LogicManager

package Parser {
Class CompanyListParser
Class ABCCommandParser

LogicManager -->CompanyListParser
CompanyListParser..>ABCCommandParser : creates >

ABCCommandParser..>CliSyntax
ABCCommandParser..>ParserUtil
ABCCommandParser-->ArgumentMultimap : creates >
ABCCommandParser..>ArgumentTokenizer
ABCCommandParser-|>"<<interface>>\nParser"
CliSyntax --> Prefix
ParserUtil ..> Prefix
ArgumentTokenizer ..> Prefix
ArgumentTokenizer .left.> ArgumentMultimap

}

package Command {
Class CommandResult

ABCCommandParser .down.> ABCCommand : creates >
LogicManager ..> "{abstract}\nCommand" : executes >
ABCCommand -up|>"{abstract}\nCommand"
ABCCommand ..> CommandResult : produces >

}
}

package Model{
Class HiddenModel #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside .right.> Logic

LogicManager .up.|> Logic

LogicManager --> Model
note left of ABCCommand: ABCCommand = AddCompanyCommand, \nAddRoleCommand, etc

Logic ..> CommandResult
LogicManager ..> CommandResult
@enduml
