@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Class "<<interface>>\nReadOnlyAddressBook" as ReadOnlyAddressBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class AddressBook
Class ModelManager
Class UserPrefs

Class UniqueCandidateList
Class Candidate
Class StudentId
Class Name
Class Phone
Class Email
Class Course
Class Seniority
Class ApplicationStatus
Class InterviewStatus
Class Availability

Class UniqueInterviewList
Class Interview

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -left-> "1" AddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniqueInterviewList
UniqueInterviewList --> "~* all" Interview

AddressBook *--> "1" UniqueCandidateList
UniqueCandidateList -left-> "~* all" Candidate
Candidate *--> StudentId
Candidate *--> Name
Candidate *--> Phone
Candidate *--> Email
Candidate *--> Course
Candidate *--> Seniority
Candidate *--> ApplicationStatus
Candidate *--> InterviewStatus
Candidate *--> "*" Availability

StudentId -[hidden]right-> Name
Name -[hidden]right-> Phone
Phone -[hidden]right-> Email
Email -[hidden]right-> Course
Course -[hidden]right-> Seniority
Seniority -[hidden]right-> ApplicationStatus
ApplicationStatus -[hidden]right-> InterviewStatus
InterviewStatus -[hidden]right-> Availability

ModelManager -->"~* filtered" Candidate
ModelManager -left->"~* filtered" Interview

@enduml
