@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Class AddressBook
Class ModelManager

Package PositionDataType <<Rectangle>>{

Class UniquePositionList
Class Position
Class Description
Class PositionName
Class PositionOffers
Class PositionOpenings
Class Requirement
}

ModelManager -->"~* filtered" Position

AddressBook *--> "1" UniquePositionList
UniquePositionList --> "~* all" Position
Position *--> Description
Position *--> PositionName
Position *--> PositionOffers
Position *--> PositionOpenings
Position *--> "*" Requirement

ModelManager -left-> "1" AddressBook

PositionName -[hidden]right-> Description

@enduml
