@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package StudentBook <<Rectangle>>{
Class "<<interface>>\nReadOnlyStudentBook" as ReadOnlyStudentBook
Class StudentBook

Class UniqueStudentList
Class Student
Class Address
Class Email
Class Name
Class Phone
Class Tag

}

Class HiddenOutside1 #FFFFFF
Class HiddenOutside2 #FFFFFF
HiddenOutside2 -right[hidden]- HiddenOutside1
HiddenOutside1 .right.> ReadOnlyStudentBook
HiddenOutside1 -right-> "1" StudentBook
HiddenOutside1 -right-> "filtered ~*" Student

StudentBook .up.|> ReadOnlyStudentBook

StudentBook *--> "1" UniqueStudentList
UniqueStudentList --> "~* all" Student
Student *--> Name
Student *--> Phone
Student *--> Email
Student *--> Address
Student *--> "*" Tag

@enduml
