@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Class "<<interface>>\nReadOnlyMedBook" as ReadOnlyMedBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class MedBook
Class ModelManager
Class UserPrefs

Class UniqueXYZList
Class XYZ


}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

MedBook .up.|> ReadOnlyMedBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyMedBook
ModelManager -left-> "1" MedBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

MedBook *--> "1" UniqueXYZList
UniqueXYZList --> "~* all" XYZ

ModelManager -->"~* filtered" XYZ
@enduml
