@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR


Package Model <<Rectangle>>{
Class "<<interface>>\nReadOnlyCompanyList" as ReadOnlyCompanyList
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class CompanyList
Class ModelManager
Class UserPrefs

Package Company\n <<Rectangle>>{
Class Company
}
Class UniqueCompanyList

Package RoleManager\n <<Rectangle>> {
Class RoleManager
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

CompanyList .up.|> ReadOnlyCompanyList

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyCompanyList
ModelManager -left-> "1" CompanyList
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

CompanyList *--> "1" UniqueCompanyList
UniqueCompanyList --> "~* all" Company
Company *-right-> "1" RoleManager



ModelManager -->"~* filtered" Company
@enduml
