@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Class HireLah
Class ModelManager

Package InterviewDataType <<Rectangle>>{

Class UniqueInterviewList
Class Interview
Class Applicant
Class Position
Class Status
}

ModelManager -->"~* filtered" Interview

HireLah *--> "1" UniqueInterviewList
UniqueInterviewList --> "~* all" Interview
Interview *--> Status
Interview *--> "1" Applicant
Interview *--> "1" Position

Applicant -[hidden]right-> Position
Position -[hidden]right-> Status

ModelManager -right-> "1" HireLah

@enduml
