@startuml
!include Style.puml

$OverrideTheme(LOGIC_COLOR)

class "{abstract}\nCommand" as Command<<Logic>>
class XYZCommand<<Logic>>

package "Parser classes"<<Logic>> {
    class "<<interface>>\nParser" as Parser<<Logic>>
    class IBookParser<<Logic>>
    class XYZCommandParser<<Logic>>
    class CliSyntax<<Logic>>
    class ParserUtil<<Logic>>
    class ArgumentMultimap<<Logic>>
    class ArgumentTokenizer<<Logic>>
    class Prefix<<Logic>>
}

class HiddenOutside<<Hidden>>
HiddenOutside ..> IBookParser

IBookParser .down.> XYZCommandParser: creates >

XYZCommandParser ..> XYZCommand : creates >
IBookParser ..> Command : returns >
XYZCommandParser .up.|> Parser
XYZCommandParser ..> ArgumentMultimap
XYZCommandParser ..> ArgumentTokenizer
ArgumentTokenizer .left.> ArgumentMultimap
XYZCommandParser ..> CliSyntax
CliSyntax ..> Prefix
XYZCommandParser ..> ParserUtil
ParserUtil .down.> Prefix
ArgumentTokenizer .down.> Prefix
XYZCommand -up-|> Command
@enduml
