@startuml
!include style.puml

$OverrideTheme(LOGIC_COLOR)

class "{abstract}\nCommand" as Command
class XYZCommand

package "Parser classes" {
    class "<<interface>>\nParser" as Parser
    class IBookParser
    class XYZCommandParser
    class CliSyntax
    class ParserUtil
    class ArgumentMultimap
    class ArgumentTokenizer
    class Prefix
}

class HiddenOutside<<Hidden>>
HiddenOutside ..> IBookParser

IBookParser .down.> XYZCommandParser: creates >

XYZCommandParser ..> XYZCommand : creates >
IBookParser ..> Command : returns >
XYZCommandParser .up.|> Parser
XYZCommandParser ..> ArgumentMultimap
XYZCommandParser ..> ArgumentTokenizer
ArgumentTokenizer .left.> ArgumentMultimap
XYZCommandParser ..> CliSyntax
CliSyntax ..> Prefix
XYZCommandParser ..> ParserUtil
ParserUtil .down.> Prefix
ArgumentTokenizer .down.> Prefix
XYZCommand -up-|> Command
@enduml
