@startuml
!include style.puml

box UI UI_COLOR_T1
participant ":MainWindow" as MainWindow UI_COLOR
end box

box UI UI_COLOR_T2
participant ":PieChartWindow" as PieChartWindow UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":SummariseCommand" as SummariseCommand LOGIC_COLOR
end box

[-> MainWindow : executeCommand()
activate MainWindow

MainWindow -> MainWindow : handleSummarise()
activate MainWindow

MainWindow -> SummariseCommand : shouldOpenPieChartWindow()
activate SummariseCommand

SummariseCommand --> MainWindow : Should display window
deactivate SummariseCommand

alt#Gold #LightBlue Should display window

create PieChartWindow
MainWindow -> PieChartWindow : new


activate PieChartWindow

PieChartWindow -> SummariseCommand : getCovidStatsByBlockDataList()
activate SummariseCommand

SummariseCommand --> PieChartWindow
deactivate SummariseCommand

PieChartWindow -> SummariseCommand : getPositiveStatsByFacultyData()
activate SummariseCommand

SummariseCommand --> PieChartWindow
deactivate SummariseCommand

PieChartWindow -> PieChartWindow : execute()
activate PieChartWindow

PieChartWindow -> PieChartWindow : collateBlocksChart()
activate PieChartWindow

PieChartWindow -> PieChartWindow : makePieChart(treemap, string)
activate PieChartWindow

PieChartWindow --> PieChartWindow : pieChart
deactivate PieChartWindow

PieChartWindow --> PieChartWindow
deactivate PieChartWindow

PieChartWindow -> PieChartWindow : createFacultyChartPositive()
activate PieChartWindow

PieChartWindow -> PieChartWindow : makePieChart(treemap, string)
activate PieChartWindow

PieChartWindow --> PieChartWindow : pieChart
deactivate PieChartWindow

PieChartWindow --> PieChartWindow : hbox

deactivate PieChartWindow

PieChartWindow -> PieChartWindow : makePieChartScene(allPieCharts)
activate PieChartWindow

PieChartWindow --> PieChartWindow
deactivate PieChartWindow

PieChartWindow --> PieChartWindow
deactivate PieChartWindow
PieChartWindow --> MainWindow: pieChartWindow
deactivate PieChartWindow


MainWindow -> PieChartWindow : show()
activate PieChartWindow

MainWindow <--PieChartWindow : result
deactivate PieChartWindow

else #Pink Else

end
deactivate MainWindow
[<--MainWindow : feedback to user
deactivate MainWindow
@enduml
