@startuml
!include style.puml

$OverrideTheme(MODEL_COLOR)

class "<<interface>>\nPredicate" as Predicate
class "{abstract}\nAttributeFilter" as AttributeFilter
class ProductFilter

class CategoryFilter
class DescriptionFilter
class ExpiredFilter
class ExpiringFilter
class NameFilter
class OutOfStockFilter
class PriceFilter
class PriceRangeFilter

ProductFilter .up.|> Predicate
AttributeFilter .up.|> Predicate

ProductFilter *-down-> "*" AttributeFilter

CategoryFilter -up-|> AttributeFilter
NameFilter -up-|> AttributeFilter
PriceFilter -up-|> AttributeFilter
PriceRangeFilter -up-|> AttributeFilter
DescriptionFilter -up-|> AttributeFilter

ExpiredFilter -|> AttributeFilter
ExpiringFilter --|> AttributeFilter
OutOfStockFilter -left-|> AttributeFilter

@enduml
