@startuml
!include style.puml

mainframe **sd**  Removal of matching tags

box Logic LOGIC_COLOR_T1
participant "t:RemoveTagCommand" as RemoveTagCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "p2:Person" as Person MODEL_COLOR
participant ":Model" as Model MODEL_COLOR
end box

activate RemoveTagCommand

create Person
RemoveTagCommand -> Person
activate Person
Person --> RemoveTagCommand : p2
deactivate Person

RemoveTagCommand -> RemoveTagCommand : remove matching tags from p2
activate RemoveTagCommand
RemoveTagCommand --> RemoveTagCommand : new_p2
deactivate RemoveTagCommand

RemoveTagCommand -> Model : setPerson(p2, new_p2)
activate Model
Model --> RemoveTagCommand
deactivate Model

create CommandResult
RemoveTagCommand -> CommandResult
activate CommandResult

CommandResult --> RemoveTagCommand
deactivate CommandResult

@enduml
