@startuml
'https://plantuml.com/sequence-diagram

Person -> SkillSet : getSkillProficiency(skill)
loop for every skill in SkillSet
    SkillSet -> Skill : isSameSkill(skill)
    SkillSet <-- Skill
end
Person <-- SkillSet

@enduml
