@startuml
'https://plantuml.com/activity-diagram-beta

start
:User enters sort command;
:Parse command arguments;

if () then ([has order Prefixes]])
    :Saves comparators in a Map;
else ([else])
endif
if () then ([has prefix '/so'])
    :Reorder the Map;
else ([else])
endif
:Use the Map to create Comparators in order;
:return then execute the Sort command;
:Update show list;
stop

@enduml
