@startuml
!include Style.puml

$OverrideTheme(STORAGE_COLOR)

package Storage as StoragePackage<<Store>> {

    class "<<interface>>\nStorage" as Storage<<Storage>>
    class StorageManager<<Storage>>

    package "UserPrefsStorage" as UserPrefsStorage<<Store>> #F4F6F6{
        class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage<<Storage>>
        class JsonUserPrefsStorage<<Storage>>
    }

    package "IBookStorage" as IBookStorage<<Store>> #F4F6F6{
        class "<<interface>>\nIBookStorage" as IBookStorage<<Storage>>
        class JsonIBookStorage<<Storage>>
        class JsonSerializableIBook<<Storage>>
        class JsonAdaptedProduct<<Storage>>
        class JsonAdaptedItem<<Storage>>
    }

}

class HiddenOutside<<Hidden>>
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" IBookStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> IBookStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonIBookStorage .up.|> IBookStorage
JsonIBookStorage ..> JsonSerializableIBook
JsonSerializableIBook --> "*" JsonAdaptedProduct
JsonAdaptedProduct --> "*" JsonAdaptedItem

@enduml
