@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager
Class JsonAdaptedTag

package "BuyerAddressBook Storage" #F4F6F6{
Class "<<interface>>\nBuyerAddressBookStorage" as BuyerAddressBookStorage
Class JsonBuyerAddressBookStorage
Class JsonSerializableBuyerAddressBook
Class JsonAdaptedBuyer
}

package "SellerAddressBook Storage" #F4F6F6{
Class "<<interface>>\nSellerAddressBookStorage" as SellerAddressBookStorage
Class JsonSellerAddressBookStorage
Class JsonSerializableSellerAddressBook
Class JsonAdaptedSeller
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" BuyerAddressBookStorage
StorageManager -up-> "1" SellerAddressBookStorage

Storage -up-|> UserPrefsStorage
Storage -right-|> BuyerAddressBookStorage
Storage -left-|> SellerAddressBookStorage

JsonUserPrefsStorage .down.|> UserPrefsStorage
JsonBuyerAddressBookStorage .up.|> BuyerAddressBookStorage
JsonBuyerAddressBookStorage ..> JsonSerializableBuyerAddressBook
JsonSerializableBuyerAddressBook --> "*" JsonAdaptedBuyer
JsonAdaptedBuyer --> "*" JsonAdaptedTag

JsonSellerAddressBookStorage .up.|> SellerAddressBookStorage
JsonSellerAddressBookStorage ..> JsonSerializableSellerAddressBook
JsonSerializableSellerAddressBook --> "*" JsonAdaptedSeller
JsonAdaptedSeller --> "*" JsonAdaptedTag

@enduml
