@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "ShowList Storage" #F4F6F6{
Class "<<interface>>\nShowListStorage" as ShowListStorage
Class JsonShowListStorage
Class JsonSerializableShowList
Class JsonAdaptedShow
Class JsonAdaptedTag
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" ShowListStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> ShowListStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonShowListStorage .up.|> ShowListStorage
JsonShowListStorage ..> JsonSerializableShowList
JsonSerializableShowList --> "*" JsonAdaptedShow
JsonAdaptedShow --> "*" JsonAdaptedTag

@enduml
