@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant "CommandType" as CommandType LOGIC_COLOR
participant ":ViewCommandParser" as ViewCommandParser LOGIC_COLOR
participant "v:ViewCommand" as ViewCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("view i/S1234567L")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("view i/S1234567L")
activate AddressBookParser

AddressBookParser -> CommandType : parseViewCommandType("view i/S1234567L")
activate CommandType

create ViewCommandParser
CommandType -> ViewCommandParser : parse("view i/S1234567L")
activate ViewCommandParser

create ViewCommand
ViewCommandParser -> ViewCommand
activate ViewCommand

ViewCommand --> ViewCommandParser : v
deactivate ViewCommand

ViewCommandParser --> CommandType : v
deactivate ViewCommandParser
ViewCommandParser -[hidden]-> CommandType
destroy ViewCommandParser

CommandType --> AddressBookParser : v
deactivate CommandType

AddressBookParser --> LogicManager : v
deactivate AddressBookParser

LogicManager -> ViewCommand : execute()
activate ViewCommand

ViewCommand -> Model : updateSummary(nric)
activate Model

Model --> ViewCommand
deactivate Model

create CommandResult
ViewCommand -> CommandResult
activate CommandResult

CommandResult --> ViewCommand
deactivate CommandResult

ViewCommand --> LogicManager : result
deactivate ViewCommand

[<--LogicManager
deactivate LogicManager
@enduml
