@startuml
'https://plantuml.com/activity-diagram-beta

start
:User input summarise command;

if () then ([User inputted additional parameters\nbesides just "summarise"])
    : Tracey throws ParseException;

    else ([Else])
    :Tracey collates total number of students with covid;
    :Tracey collates number of students in each\nhall block under each covid status category;
    :Tracey collates number of covid positive\nstudents in each faculty;

    If () then ([There is an address book\nto collect data])
        :Create pie charts and bar chart with the data;
        :Create pop up window to show the chart(s);

        else ([Else])
        :Form a FAIL message;

        endif
        :A summary is produced;
endif
:A response is returned to user;
stop

@enduml
