@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class " ListPanel<T> " as ListPanel
Class ScheduleItemListPanel
Class " <<interface>>\nRecyclableCard<T> " as RecyclableCard
Class " <<interface>>\nCardFactory<T> " as CardFactory
Class StatusBarFooter
Class CommandBox
package "Model UI Cards" as ModelCards <<Rectangle>> {
    Class HiddenCard #FFFFFF
}
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}



Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
MainWindow *-down->  "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> "2" ListPanel
MainWindow *-down-> "1" ScheduleItemListPanel
MainWindow *-down-> "1" StatusBarFooter
MainWindow --> "0..1" HelpWindow

ListPanel -down-> "*" RecyclableCard
ListPanel -down-> "1" CardFactory
CardFactory -left->  "*" RecyclableCard : Creates >
ModelCards .up.|> RecyclableCard
ModelCards .up.|> CardFactory

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
ListPanel --|> UiPart
ModelCards -left-|> UiPart
StatusBarFooter --|> UiPart
HelpWindow --|> UiPart

HiddenCard .right.> Model
UiManager -right-> Logic
MainWindow -left-> Logic

ScheduleItemListPanel -left-|> ListPanel
ListPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter

MainWindow -[hidden]-|> UiPart
@enduml
