@startuml
!include Style.puml

$OverrideTheme(UI_COLOR)

package UI as UiPackage<<Ui>> {
    class "<<interface>>\nUi" as Ui<<Ui>>
    class "{abstract}\nUiPart" as UiPart<<Ui>>
    class "{abstract}\nUiComponent" as UiComponent<<Ui>>
    class UiManager<<Ui>>
    class MainWindow<<Ui>>
    class MenuToolbar<<Ui>>
    class CommandBox<<Ui>>
    class ResultWindow<<Ui>>

    class Table<<Ui>>
    class Popup<<Ui>>
}

class Model<<Model>>
class Logic<<Logic>>

class HiddenOutside<<Hidden>>
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
MainWindow *--> "1" MenuToolbar
MainWindow *--> "1" CommandBox
MainWindow *--> "1" ResultWindow
MainWindow --> Table
MainWindow -right-> Popup

MenuToolbar --up-|> UiComponent
CommandBox --up-|> UiComponent
ResultWindow --up-|> UiComponent

MainWindow -up-|> UiPart
UiComponent -up-|> UiPart

UiManager -right-> Logic
MainWindow --> Logic
Popup ..> Logic
Popup --[hidden]-> Table

MainWindow ..> Model
Popup ...> Model
Table .right.> Model

UiComponent -left-> MainWindow

@enduml
