@startuml
!include style.puml
!theme materia-outline

skinparam backgroundColor white
skinparam shadowing false
skinparam arrowThickness 1.1

package UI <<Rectangle>> {
   Class "<<interface>>\nUi" as Ui
   Class "{abstract}\nUiPart" as UiPart
   Class "{abstract}\nUiComponent" as UiComponent
   Class UiManager
   Class MainWindow
   Class MenuToolbar
   Class CommandBox
   Class ResultWindow

   package Table <<Rectangle>> {
   }

   package Popup <<Rectangle>> {
   }
}

skinparam Class<<Hidden>> {
   BorderColor #FFFFFF
   BackgroundColor #FFFFFF
   FontColor #FFFFFF
   HeaderBackgroundColor #FFFFFF
   StereotypeFontColor #FFFFFF
}

package Model <<Rectangle>> {
}

package Logic <<Rectangle>> {
}


Class HiddenOutside<<Hidden>>
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
MainWindow *--> "1" MenuToolbar
MainWindow *--> "1" CommandBox
MainWindow *--> "1" ResultWindow
MainWindow --> Table
MainWindow --> Popup

MenuToolbar -up-|> UiComponent
CommandBox -up-|> UiComponent
ResultWindow -up-|> UiComponent

MainWindow -up-|> UiPart
UiComponent -up-|> UiPart

UiManager --> Logic
MainWindow --> Logic
Popup .right.> Logic

MainWindow .[norank].> Model
Popup .right.> Model
Table .down.> Model

UiComponent -left-> MainWindow

@enduml
