@startuml
!include Style.puml

$OverrideTheme(UI_COLOR)

package UI as UiPackage<<Ui>> {
    class "{abstract}\nUiComponent" as UiComponent<<Ui>>
    class MainWindow<<Ui>>

    package Popup as PopupContainer<<Ui>> {
       class "{abstract}\nPopup" as Popup<<Ui>>
       class PopupHandler<<Ui>>
       class PopupAdd<<Ui>>
       class PopupDelete<<Ui>>
       class PopupUpdate<<Ui>>
    }
}

class Model<<Model>>
class Logic<<Logic>>

MainWindow *--> "1" PopupHandler

PopupHandler *-->  "1" PopupAdd
PopupHandler *-->  "1" PopupDelete
PopupHandler *-->  "1" PopupUpdate

PopupAdd -up-|> Popup
PopupDelete -up-|> Popup
PopupUpdate -up-|> Popup

Popup -up-|> UiComponent


PopupAdd ..> Logic
PopupUpdate ..> Model
PopupUpdate ..> Logic
PopupDelete ..> Model
PopupDelete ..> Logic

UiComponent -left-> MainWindow

@enduml
