@startuml
!include style.puml
!theme materia-outline

skinparam backgroundColor white
skinparam shadowing false
skinparam arrowThickness 1.1

package UI {
    Class "{abstract}\nUiComponent" as UiComponent
    Class MainWindow
    package Table <<Rectangle>> {
        Class ProductCard
        Class Table
        Class TableContent
        Class TableHeader
    }
}

package Model <<Rectangle>> {
}

package Logic <<Rectangle>> {
}

MainWindow *-right-> "1" Table

Table *--> "1" TableContent
Table *--> "1" TableHeader

TableContent *-> "*" ProductCard

ProductCard --|> UiComponent
Table --|> UiComponent
TableContent --|> UiComponent
TableHeader --|> UiComponent

TableContent ..> Model
MainWindow ..> Model
ProductCard ..> Model

UiComponent -left-> MainWindow

MainWindow -right-> Logic

@enduml
