@startuml
!include Style.puml

$OverrideTheme(UI_COLOR)

package UI as UiPackage<<Ui>> {
    class "{abstract}\nUiComponent" as UiComponent<<Ui>>
    class MainWindow<<Ui>>

    package Table as Table<<Ui>> {
        class ProductCard<<Ui>>
        class Table<<Ui>>
        class TableContent<<Ui>>
        class TableHeader<<Ui>>
    }
}

class Model<<Model>>
class Logic<<Logic>>

MainWindow *-right-> "1" Table

Table *--> "1" TableContent
Table *--> "1" TableHeader

TableContent *--> "*" ProductCard

ProductCard --|> UiComponent
Table --|> UiComponent
TableContent --|> UiComponent
TableHeader --|> UiComponent

TableContent ..> Model
MainWindow ..> Model
ProductCard ..> Model

UiComponent -left-> MainWindow

MainWindow -right-> Logic

@enduml
