@startuml
start
:User inputs commands;
:System pushes command into StackUndoRedo;


if () then ([command shows add or edit window])
    :Command will not be
    added to undoStack;
else ([else])
    if () then ([else])
        :Clear redoStack;
    else ([is UndoCommand or RedoCommand])

    endif

    if () then ([is not redoable])
        :Command will not be
        added to undoStack;
    else ([else])
        :Command push into undoStack;
    endif
endif
stop
@enduml
