@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After "redo"

package AddressBook <<rectangle>> {
    class State1 as "persons: state B"
    class State2 as "personsHistory: null"
    class State3 as "personsOriginal: null"
}

State1 -[hidden]right-> State2
State2 -[hidden]right-> State3

@end
