@startuml
!include style.puml

skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "clear"

package stateChanges {
    class StateChange1 as "__sc0:StateChange__"
    class StateChange2 as "__sc1:StateChange__"
    class StateChange3 as "__sc2:StateChange__"
}
StateChange1 -[hidden]right-> StateChange3
StateChange3 -[hidden]right-> StateChange2
hide StateChange2

class Pointer as "currentStateChange" #FFFFFF
Pointer -up-> StateChange3
note right on link: StateChange sc1 is deleted
@end
