@startuml
hide circle


Command <|-- RedoableCommand

class Command {
  # undoRedoStack: StackUndoRedo
  + execute(): CommandResult
  + setData(): void
}


skinparam classAttributeIconSize 0
class RedoableCommand
 {
   - previousAddressBook: ReadOnlyAddressBook
   - previousArchiveBook: ReadOnlyAddressBook
   - isSwapped: boolean
   - saveAddressBookSnapshot(): void
   # undo(): void
   # redo(): void
   + execute(): CommandResult
}
@enduml
