@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":IBookParser" as IBookParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":ReversibleIBook" as ReversibleIBook MODEL_COLOR
participant ":StateChangeRecorder" as StateChangeRecorder MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> IBookParser : parseCommand(undo)
activate IBookParser

create UndoCommand
IBookParser -> UndoCommand
activate UndoCommand

UndoCommand --> IBookParser
deactivate UndoCommand

IBookParser --> LogicManager : u
deactivate IBookParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoIBook()
activate Model

Model -> ReversibleIBook : undo()
activate ReversibleIBook

ReversibleIBook -> StateChangeRecorder :getCurrentReverseActionList()
activate StateChangeRecorder

StateChangeRecorder --> ReversibleIBook
deactivate StateChangeRecorder

ReversibleIBook -> ReversibleIBook :carries out reverse actions
ReversibleIBook --> Model :
deactivate ReversibleIBook

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
