@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":PetBookParser" as PetBookParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedPetBook" as VersionedPetBook MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> PetBookParser : parseCommand(undo)
activate PetBookParser

create UndoCommand
PetBookParser -> UndoCommand
activate UndoCommand

UndoCommand --> PetBookParser
deactivate UndoCommand

PetBookParser --> LogicManager : u
deactivate PetBookParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undo()
activate Model

Model -> VersionedPetBook : undo()
activate VersionedPetBook

VersionedPetBook -> VersionedPetBook :resetData(ReadOnlyPetBook)
VersionedPetBook --> Model :
deactivate VersionedPetBook

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
