@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ClientAddressBookParser" as ClientAddressBookParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedClientAddressBook" as VersionedClientAddressBook MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> ClientAddressBookParser : parseCommand(undo)
activate AddressBookParser

create UndoCommand
AddressBookParser -> UndoCommand
activate UndoCommand

UndoCommand --> ClientAddressBookParser
deactivate UndoCommand

ClientAddressBookParser --> LogicManager : u
deactivate ClientAddressBookParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoClientAddressBook()
activate Model

Model -> VersionedClientAddressBook : undo()
activate VersionedClientAddressBook

VersionedClientAddressBook -> VersionedClientAddressBook :resetData(ReadOnlyClientAddressBook)
VersionedClientAddressBook --> Model :
deactivate VersionedClientAddressBook

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
