@startuml
start
:User executes Unmark command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if (Command is Valid)
    :ManageEZPZ marks the [Task] as not done;
else ([else])
endif
stop
@enduml
