@startuml
!include ../style.puml
show members
hide empty methods
hide empty fields
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

class " __:CompositeObservableList__ " as CompositeObservableList {

}

class "__slot1:AppointmentSlot__" as AppointmentSlot1 {
    period = ("12-12-2022 12:00", "12-12-2022 13:00")
}

class "__slot2:AppointmentSlot__" as AppointmentSlot2 {
    period = ("12-12-2022 14:00", "12-12-2022 14:30")
}

class "__appt1:Appointment__" as Appointment1 {
    StartDateTime = "12-12-2022 13:00"
    Duration = 60
}

class "__appt2:Appointment__" as Appointment2 {
    StartDateTime = "12-12-2022 14:30"
    Duration = 60
}

class "__:ModelManager__" as ModelManager {
}

ModelManager -down-> CompositeObservableList

CompositeObservableList -down-> AppointmentSlot1 : Index 0
CompositeObservableList -down-> Appointment1 : Index 1
CompositeObservableList -down-> AppointmentSlot2 : Index 2
CompositeObservableList -down-> Appointment2 : Index 3

AppointmentSlot1 -[hidden]right-> Appointment1
Appointment1 -[hidden]right-> AppointmentSlot2
AppointmentSlot2 -[hidden]right-> Appointment2

@enduml
