@startuml
!include ../style.puml
show fields
hide empty fields
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title Before shiftAppointmentToPosition(2)

class "  __:DisjointAppointmentList__  " as DisjointAppointmentList

package "addAppointment(appt2) Before ShiftAppointmentToPosition()" {
    class Appointment0 as "  __appt0:Appointment__  " {
        StartDateTime = "12-12-2022 13:00"
        Duration = 30
    }
    note top: Index 0
    class Appointment1 as "  __appt1:Appointment__  " {
        StartDateTime = "12-12-2022 13:30"
        Duration = 60
    }
    note top: Index 1
    class Appointment2 as "  __appt2:Appointment__  " #FFCCCC {
        StartDateTime = "10-11-2022 15:30"
        Duration = 10
    }
    note top: Index 2
}
Appointment0 -[hidden]right-> Appointment1
Appointment1 -[hidden]right-> Appointment2
Appointment1 -[hidden]down-> DisjointAppointmentList

DisjointAppointmentList -left-> Appointment0
DisjointAppointmentList -up-> Appointment1
DisjointAppointmentList -right-> Appointment2
note right on link: appt2 the only\n appointment \n is out of position.

@end
