title: "HRConnect"
theme: jekyll-theme-architect

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2122S2-CS2103T-W11-2/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
