title: "InternBuddy"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "CS2103T-W14-3/tp/"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
