title: "CinnamonBun"
theme: jekyll-theme-dinky

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2122S2-CS2103T-W09-2/tp"
github_icon: "images/github-icon.png"
show_downloads: true

plugins:
  - jemoji
