title: "Tracey"
theme: jekyll-theme-hacker

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2122S2-CS2103T-T12-3/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji

